# This is a basic workflow to help you get started with Actions

name: CLA

on:
  pull_request_target

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: havogt/allowlist-action@master
      with:
        allowlist-url: https://raw.githubusercontent.com/havogt/allow-list-action-example/master/allowlist.txt
